const LIKE_POST = 'LIKE_POST';
const LIKE_COMMENT = 'LIKE_COMMENT';
const COMMENT = 'COMMENT';
const SEND_MESSAGE = 'SEND_MESSAGE';
const FRIEND_REQUEST = 'FRIEND_REQUEST';
const FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED';
const MESSAGE = 'MESSAGE';

module.exports = {
  LIKE_POST,
  LIKE_COMMENT,
  COMMENT,
  SEND_MESSAGE,
  FRIEND_REQUEST,
  FRIEND_REQUEST_ACCEPTED,
  MESSAGE,
};
