const LIKE_POST = 'LIKE_POST';
const LIKE_COMMENT = 'LIKE_COMMENT';
const COMMENT_ON_MY_POST = 'COMMENT_ON_MY_POST';
const COMMENT_ON_SAME_POST = 'COMMENT_ON_SAME_POST';
const SEND_MESSAGE = 'SEND_MESSAGE';
const FRIEND_REQUEST = 'FRIEND_REQUEST';
const FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED';
const MESSAGE = 'MESSAGE';

module.exports = {
  LIKE_POST,
  LIKE_COMMENT,
  COMMENT_ON_MY_POST,
  SEND_MESSAGE,
  FRIEND_REQUEST,
  FRIEND_REQUEST_ACCEPTED,
  COMMENT_ON_SAME_POST,
  MESSAGE,
};
