// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const TOKEN_FROM_STORAGE = 'TOKEN_FROM_STORAGE';
export const AUTH_LOADING = 'AUTH_LOADING';

// Users
export const LOAD_MY_USER_SUCCESS = 'LOAD_MY_USER_SUCCESS';
export const LOAD_MY_USER_FAILURE = 'LOAD_MY_USER_FAILURE';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE';
export const LOAD_CURRENTLY_VIEWING_USER_SUCCESS =
  'LOAD_CURRENTLY_VIEWING_USER_SUCCESS';
export const LOAD_CURRENTLY_VIEWING_USER_FAILURE =
  'LOAD_CURRENTLY_VIEWING_USER_FAILURE';
export const SET_MY_USER = 'SET_MY_USER';
export const USER_LOADING = 'USER_LOADING';

// Posts, newsfeed, comment, like
export const LOAD_NEWSFEED_SUCCESS = 'LOAD_NEWSFEED_SUCCESS';
export const LOAD_NEWSFEED_FAILURE = 'LOAD_NEWSFEED_FAILURE';
export const LOAD_A_POST_SUCCESS = 'LOAD_A_POST_SUCCESS';
export const LOAD_A_POST_FAILURE = 'LOAD_A_POST_FAILURE';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FAILURE = 'LOAD_POSTS_FAILURE';
export const ADDED_NEW_POST = 'ADDED_NEW_POST';
export const LIKED_POST = 'LIKED_POST';
export const COMMENTED_POST = 'COMMENTED_POST';
export const POST_LOADING = 'POST_LOADING';

// Notification
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';

// Messages
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const NEW_MESSAGE = 'NEW_MESSAGE';
export const LOAD_CURRENT_MESSAGE_USER = 'LOAD_CURRENT_MESSAGE_USER';

// Clear data
export const CLEAR_DATA = 'CLEAR_DATA';
