// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const TOKEN_FROM_STORAGE = 'TOKEN_FROM_STORAGE';

// Users
export const LOAD_MY_USER_SUCCESS = 'LOAD_MY_USER_SUCCESS';
export const LOAD_MY_USER_FAILURE = 'LOAD_MY_USER_FAILURE';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE';
