export const LIKE_POST = 'LIKE_POST';
export const LIKE_COMMENT = 'LIKE_COMMENT';
export const COMMENT_ON_MY_POST = 'COMMENT_ON_MY_POST';
export const COMMENT_ON_SAME_POST = 'COMMENT_ON_SAME_POST';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const FRIEND_REQUEST = 'FRIEND_REQUEST';
export const FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED';
export const MESSAGE = 'MESSAGE';
